import PDFDocument from "pdfkit";

export const generatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 40,
      info: {
        Author: "CalibAI",
        Title: data?.title,
        Creator: "CalibAI",
      }
    });

    const bufferChunks = [];

    doc.on("data", (buffer) => bufferChunks.push(buffer));

    doc.on("end", () => resolve(Buffer.concat(bufferChunks)));

    doc.on("error", reject);

    // Title
    doc.fontSize(28).text(data?.title, { align: "center" }).fillColor("#111827");

    // Give a space if there is subtitle
    if (data?.subtitle) {
      doc.moveDown(0.5);
      // Subtitle
      doc.fontSize(14).text(data?.subtitle, { align: "center" }).fillColor("#6B7280");
    }

    doc.moveDown(2);

    data?.sections?.forEach((sec) => {
      // Section heading
      doc.fontSize(16).text(sec?.heading, { align: "left" }).fillColor("#111827");

      doc.moveDown(0.5);

      // Points of section
      sec?.points?.forEach((pt) => {
        doc.fontSize(12).text(`• ${pt}`, { align: "left", lineGap: 2 }).fillColor("#374151");
      });

      doc.moveDown(1);
    });

    doc.moveDown();

    // Footer
    doc.fontSize(10).text("Generated by CalibAI", { align: "center" }).fillColor("#9CA3AF");

    doc.end();
  });
};