import pptxgen from 'pptxgenjs';

const COLORS = {
  primary: "2563EB",
  secondary: "0F172A",
  text: "334155",
  light: "F8FAFC",
  border: "E2E8F0",
  white: "FFFFFF",
  muted: "647488",
  fill: "60A5FA",
  subtitle: "DBEAFE",
  blue: "BFDBFE"
};

const addCoverPage = (ppt, data) => {
  const slide = ppt.addSlide();

  slide.background = {
    color: COLORS.primary,
  }

  slide.addText(
    data?.title,
    {
      x: 0.7,
      y: 1.7,
      w: 12,
      h: 0.8,
      fontSize: 28,
      color: COLORS.white,
      bold: true,
      align: "center"
    }
  );

  slide.addText(
    data?.subtitle,
    {
      x: 1,
      y: 2.8,
      w: 11.5,
      h: 0.4,
      fontSize: 15,
      color: COLORS.subtitle,
      align: "center"
    }
  );

  slide.addText(
    "Generated by CalibAI",
    {
      x: 0,
      y: 6.9,
      w: 13.33,
      h: 0.2,
      fontSize: 10,
      color: COLORS.blue,
      align: "center"
    }
  );
}

const addContentSlide = (ppt, title, points, page, length) => {
  const slide = ppt.addSlide();

  slide.background = {
    color: COLORS.white,
  }

  slide.addShape(
    ppt.ShapeType.rect,
    {
      x: 0,
      y: 0,
      w: 13.33,
      h: 0.18,
      fill: { color: COLORS.fill },
      line: { color: COLORS.fill },
    }
  );

  slide.addText(
    title,
    {
      x: 0.6,
      y: 0.35,
      w: 10,
      h: 0.4,
      fontSize: 24,
      color: COLORS.primary,
      bold: true,
      align: "center"
    }
  );

  slide.addShape(
    ppt.ShapeType.line,
    {
      x: 0.6,
      y: 0.85,
      w: 12,
      h: 0,
      line: { color: COLORS.border, width: 1.2 },
    }
  );

  points?.forEach((point, index) => {
    const y = 1.2 + index * 0.75
    slide.addShape(
      ppt.ShapeType.round1Rect,
      {
        x: 0.7,
        y,
        w: 12,
        h: 0.58,
        fill: { color: index % 2 ? "F8FAFC" : "EFF6FF" },
        line: { color: COLORS.border },
        rectRadius: 0.08
      }
    )
    slide.addShape(ppt.ShapeType.ellipse, {
      x: 0.92,
      y: y + 0.18,
      w: 0.12,
      h: 0.12,
      fill: { color: COLORS.primary },
      line: { color: COLORS.primary },
    })
    slide.addText(
      point,
      {
        x: 1.2,
        y: y + 0.08,
        w: 11,
        h: 0.35,
        fontSize: 15,
        color: COLORS.text,
        fit: "shrink",
      }
    );
  })

  slide.addText(
    `${page}/${length}`,
    {
      x: 12.1,
      y: 6.9,
      w: 0.8,
      h: 0.2,
      fontSize: 10,
      color: COLORS.muted,
      align: "right"
    }
  );
  slide.addText(
    "CalibAI",
    {
      x: 0.6,
      y: 6.9,
      w: 2,
      h: 0.2,
      fontSize: 10,
      color: COLORS.muted,
    }
  );
};

const addThankYou = (ppt) => {
  const slide = ppt.addSlide();

  slide.background = { color: COLORS.secondary };

  slide.addText(
    "Thank You",
    {
      x: 0,
      y: 2.2,
      w: 13.33,
      h: 0.8,
      fontSize: 34,
      color: COLORS.white,
      bold: true,
      align: "center"
    }
  );

  slide.addText(
    "Generated by CalibAI",
    {
      x: 0,
      y: 6.9,
      w: 13.33,
      h: 0.2,
      fontSize: 10,
      color: COLORS.blue,
      align: "center"
    }
  );
};

export const generatePpt = async (data) => {
  const ppt = new pptxgen();
  ppt.layout = "LAYOUT_WIDE";
  ppt.author = "CalibAI";
  ppt.title = data?.title;
  ppt.subject = data?.title;
  ppt.company = "CalibAI";
  ppt.lang = "en-US";
  ppt.theme = {
    headFontFace: "Aptos",
    bodyFontFace: "Aptos",
  }

  addCoverPage(ppt, data);

  data?.slides?.forEach((slide, index) => addContentSlide(ppt, slide?.title, slide?.points, index + 1, data?.slides?.length));

  addThankYou(ppt);

  return ppt;
}