import pptxgen from 'pptxgenjs';

const THEMES = {
  blue: {
    primary: "2563EB",
    secondary: "0F172A",
    text: "334155",
    light: "F8FAFC",
    border: "E2E8F0",
    muted: "647488",
    fill: "60A5FA",
    subtitle: "DBEAFE",
    accent: "BFDBFE"
  },
  red: {
    primary: "DC2626",
    secondary: "1C1917",
    text: "334155",
    light: "F8FAFC",
    border: "E2E8F0",
    muted: "647488",
    fill: "F87171",
    subtitle: "FEE2E2",
    accent: "FECACA"
  },
  green: {
    primary: "16A34A",
    secondary: "0F172A",
    text: "334155",
    light: "F8FAFC",
    border: "E2E8F0",
    muted: "647488",
    fill: "4ADE80",
    subtitle: "DCFCE7",
    accent: "BBF7D0"
  },
  yellow: {
    primary: "CA8A04",
    secondary: "1C1917",
    text: "334155",
    light: "F8FAFC",
    border: "E2E8F0",
    muted: "647488",
    fill: "FACC15",
    subtitle: "FEF9C3",
    accent: "FEF08A"
  },
  purple: {
    primary: "9333EA",
    secondary: "1C1917",
    text: "334155",
    light: "F8FAFC",
    border: "E2E8F0",
    muted: "647488",
    fill: "C084FC",
    subtitle: "F3E8FF",
    accent: "E9D5FF"
  },
  black: {
    primary: "18181B",
    secondary: "09090B",
    text: "334155",
    light: "F8FAFC",
    border: "E2E8F0",
    muted: "647488",
    fill: "52525B",
    subtitle: "F4F4F5",
    accent: "E4E4E7"
  }
};

const getRandomTheme = () => {
  const themeKeys = Object.keys(THEMES);
  const randomKey = themeKeys[Math.floor(Math.random() * themeKeys.length)];
  return THEMES[randomKey];
};

const addCoverPage = (ppt, data, colors) => {
  const slide = ppt.addSlide();

  slide.background = {
    color: colors.primary,
  }

  slide.addText(
    data?.title,
    {
      x: 0.7,
      y: 1.7,
      w: 12,
      h: 0.8,
      fontSize: 28,
      color: colors.light,
      bold: true,
      align: "center"
    }
  );

  slide.addText(
    data?.subtitle,
    {
      x: 1,
      y: 2.8,
      w: 11.5,
      h: 0.4,
      fontSize: 15,
      color: colors.subtitle,
      align: "center"
    }
  );

  slide.addText(
    "Generated by CalibAI",
    {
      x: 0,
      y: 6.9,
      w: 13.33,
      h: 0.2,
      fontSize: 10,
      color: colors.accent,
      align: "center"
    }
  );
}

const addContentSlide = (ppt, title, points, page, length, colors) => {
  const slide = ppt.addSlide();

  slide.background = {
    color: colors.light,
  }

  slide.addShape(
    ppt.ShapeType.rect,
    {
      x: 0,
      y: 0,
      w: 13.33,
      h: 0.18,
      fill: { color: colors.fill },
      line: { color: colors.fill },
    }
  );

  slide.addText(
    title,
    {
      x: 0.6,
      y: 0.35,
      w: 10,
      h: 0.4,
      fontSize: 24,
      color: colors.primary,
      bold: true,
      align: "center"
    }
  );

  slide.addShape(
    ppt.ShapeType.line,
    {
      x: 0.6,
      y: 0.85,
      w: 12,
      h: 0,
      line: { color: colors.border, width: 1.2 },
    }
  );

  points?.forEach((point, index) => {
    const y = 1.2 + index * 0.75
    slide.addShape(
      ppt.ShapeType.round1Rect,
      {
        x: 0.7,
        y,
        w: 12,
        h: 0.58,
        fill: { color: index % 2 ? colors.light : colors.subtitle },
        line: { color: colors.border },
        rectRadius: 0.08
      }
    )
    slide.addShape(ppt.ShapeType.ellipse, {
      x: 0.92,
      y: y + 0.18,
      w: 0.12,
      h: 0.12,
      fill: { color: colors.primary },
      line: { color: colors.primary },
    })
    slide.addText(
      point,
      {
        x: 1.2,
        y: y + 0.08,
        w: 11,
        h: 0.35,
        fontSize: 15,
        color: colors.text,
        fit: "shrink",
      }
    );
  })

  slide.addText(
    `${page}/${length}`,
    {
      x: 12.1,
      y: 6.9,
      w: 0.8,
      h: 0.2,
      fontSize: 10,
      color: colors.muted,
      align: "right"
    }
  );
  slide.addText(
    "CalibAI",
    {
      x: 0.6,
      y: 6.9,
      w: 2,
      h: 0.2,
      fontSize: 10,
      color: colors.muted,
    }
  );
};

const addThankYou = (ppt, colors) => {
  const slide = ppt.addSlide();

  slide.background = { color: colors.secondary };

  slide.addText(
    "Thank You",
    {
      x: 0,
      y: 2.2,
      w: 13.33,
      h: 0.8,
      fontSize: 34,
      color: colors.light,
      bold: true,
      align: "center"
    }
  );

  slide.addText(
    "Generated by CalibAI",
    {
      x: 0,
      y: 6.9,
      w: 13.33,
      h: 0.2,
      fontSize: 10,
      color: colors.accent,
      align: "center"
    }
  );
};

export const generatePpt = async (data) => {
  const ppt = new pptxgen();
  ppt.layout = "LAYOUT_WIDE";
  ppt.author = "CalibAI";
  ppt.title = data?.title;
  ppt.subject = data?.title;
  ppt.company = "CalibAI";
  ppt.lang = "en-US";
  ppt.theme = {
    headFontFace: "Aptos",
    bodyFontFace: "Aptos",
  }

  const colors = getRandomTheme();

  addCoverPage(ppt, data, colors);

  data?.slides?.forEach((slide, index) => addContentSlide(ppt, slide?.title, slide?.points, index + 1, data?.slides?.length, colors));

  addThankYou(ppt, colors);

  return ppt;
}